version: '3'

services:
  php:
    build:
      dockerfile: './deploy/Dockerfile'
      context: '../'

  nginx:
    image: 'nginx:1.11-alpine'
    depends_on:
      - php
    ports:
      - '8080:8080'
      - '80:80'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf:ro'
      - '../:/app:ro'
