version: '3'

services:
  php:
    build:
      dockerfile: './deploy/Dockerfile'
      context: '.'
    volumes:
      - 'app-files:/var/www/html'

  nginx:
    image: 'nginx:1.11-alpine'
    depends_on:
      - php
    ports:
      - '8080:8080'
      - '80:80'
    volumes:
      - './develop/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './:/var/www/html/:ro'

volumes:
  app-files:
